trigger:
 branches:
   include:
     - 7.3.x
     
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: oc-setup@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'aws'

- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'aws'
    cmd: 'oc apply -f ${SYSTEM_DEFAULTWORKINGDIRECTORY}/kitchensink/project.yaml'
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'aws'
    cmd: 'oc new-app -p SOURCE_REPOSITORY_URL=https://github.com/samueltauil/jboss-eap-quickstarts --template=eap72-basic-s2i -p SOURCE_REPOSITORY_REF=7.3.x -p MAVEN_MIRROR_URL=http://nexus3.nexus:8081/repository/maven-public -p CONTEXT_DIR=kitchensink -p APPLICATION_NAME=kitchensink -n kitchensink'
    ignoreFlag: true   
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'aws'
    cmd: 'oc set triggers dc/kitchensink --manual'
    ignoreFlag: true
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'aws'
    cmd: 'oc rollout latest dc/kitchensink'
    ignoreFlag: true
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'aws'
    cmd: 'oc scale dc/kitchensink --replicas=3 -n kitchensink'
    ignoreFlag: true
