trigger:
 branches:
   include:
     - 7.3.x
     
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: oc-setup@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'aws'

- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'aws'
    cmd: 'oc apply -f ${SYSTEM_DEFAULTWORKINGDIRECTORY}/_my_sources/jboss-eap-quickstarts/kitchensink/project.yaml'
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'aws'
    cmd: 'oc new-app -p SOURCE_REPOSITORY_URL=https://github.com/samueltauil/jboss-eap-quickstarts --template=eap72-basic-s2i -p MAVEN_MIRROR_URL=http://nexus.nexus3:8081/repository/maven-public -p CONTEXT_DIR=kitchensink -p APPLICATION_NAME=kitchensink -n kitchensink'
    
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'aws'
    cmd: 'oc scale dc/kitchensink --replicas=3 -n kitchensink'

